apiVersion: v1
kind: Service
metadata:
  name: customauth
  labels:
    service: customauth
    project: snackbar
spec:
  type: NodePort
  selector:
    service: customauth
    project: snackbar
  ports:
    - port: 3001
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customauth
  labels:
    service: customauth
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: customauth
      project: snackbar
  template:
    metadata:
      labels:
        service: customauth
        project: snackbar
    spec:
      containers:
        - name: customauth
          image: egoomoy/custom_auth
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
